package com.ourgiant.kirocontrolpanel.mcp;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ourgiant.kirocontrolpanel.util.JsonMapperFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;
import java.util.Optional;

/**
 * Loads the MCP server catalog (generated by tools/generate-mcp-catalog.py
 * from kiro.dev's known-servers list), either from the bundled classpath
 * resource (src/main/resources/mcp-catalog.json, shipped with the app) or,
 * on demand via {@link #fetchFromUrl(String)}, live from GitHub -- since a
 * packaged desktop app can go weeks between releases, the bundled copy
 * alone can't stay current; a live fetch lets an already-installed app pull
 * whatever's on the repo's default branch right now.
 */
public class McpCatalogService {
    private static final Logger logger = LoggerFactory.getLogger(McpCatalogService.class);
    private static final String DEFAULT_RESOURCE_PATH = "/mcp-catalog.json";
    private static final Duration CONNECT_TIMEOUT = Duration.ofSeconds(5);
    private static final Duration REQUEST_TIMEOUT = Duration.ofSeconds(10);

    private final ObjectMapper mapper = JsonMapperFactory.createMapper();
    private final String resourcePath;

    private List<McpCatalogEntry> cached;

    public McpCatalogService() {
        this(DEFAULT_RESOURCE_PATH);
    }

    McpCatalogService(String resourcePath) {
        this.resourcePath = resourcePath;
    }

    public List<McpCatalogEntry> load() {
        if (cached == null) {
            cached = readFromResource();
        }
        return cached;
    }

    /** Does a real network call — run this off the EDT (e.g. from a SwingWorker). @return empty on any failure (offline, non-200, malformed JSON, ...). */
    public Optional<List<McpCatalogEntry>> fetchFromUrl(String url) {
        try {
            HttpClient client = HttpClient.newBuilder().connectTimeout(CONNECT_TIMEOUT).build();
            HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("User-Agent", "kiro-control-panel")
                .timeout(REQUEST_TIMEOUT)
                .build();
            HttpResponse<InputStream> response = client.send(request, HttpResponse.BodyHandlers.ofInputStream());
            if (response.statusCode() != 200) {
                return Optional.empty();
            }
            try (InputStream in = response.body()) {
                return Optional.of(parseEntries(in));
            }
        } catch (Exception e) {
            logger.debug("Failed to fetch MCP catalog from {}", url, e);
            return Optional.empty();
        }
    }

    private List<McpCatalogEntry> readFromResource() {
        try (InputStream in = McpCatalogService.class.getResourceAsStream(resourcePath)) {
            if (in == null) {
                logger.error("MCP catalog resource {} not found on classpath", resourcePath);
                return List.of();
            }
            return parseEntries(in);
        } catch (IOException e) {
            logger.error("Failed to read MCP catalog resource {}", resourcePath, e);
            return List.of();
        }
    }

    List<McpCatalogEntry> parseEntries(InputStream in) throws IOException {
        return mapper.readValue(in, new TypeReference<List<McpCatalogEntry>>() {
        });
    }
}
