package com.ourgiant.kirocontrolpanel.mcp;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ourgiant.kirocontrolpanel.util.JsonMapperFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

/**
 * Loads the bundled MCP server catalog (src/main/resources/mcp-catalog.json,
 * generated by tools/generate-mcp-catalog.py from kiro.dev's known-servers
 * list) from the classpath. Read-only and never live-fetched -- unlike
 * McpConfigService, there's nothing here to write back to disk.
 */
public class McpCatalogService {
    private static final Logger logger = LoggerFactory.getLogger(McpCatalogService.class);
    private static final String DEFAULT_RESOURCE_PATH = "/mcp-catalog.json";

    private final ObjectMapper mapper = JsonMapperFactory.createMapper();
    private final String resourcePath;

    private List<McpCatalogEntry> cached;

    public McpCatalogService() {
        this(DEFAULT_RESOURCE_PATH);
    }

    McpCatalogService(String resourcePath) {
        this.resourcePath = resourcePath;
    }

    public List<McpCatalogEntry> load() {
        if (cached == null) {
            cached = readFromResource();
        }
        return cached;
    }

    private List<McpCatalogEntry> readFromResource() {
        try (InputStream in = McpCatalogService.class.getResourceAsStream(resourcePath)) {
            if (in == null) {
                logger.error("MCP catalog resource {} not found on classpath", resourcePath);
                return List.of();
            }
            return mapper.readValue(in, new TypeReference<List<McpCatalogEntry>>() {
            });
        } catch (IOException e) {
            logger.error("Failed to read MCP catalog resource {}", resourcePath, e);
            return List.of();
        }
    }
}
